export enum Role {
    ROLE_USER = "ROLE_USER",
    ROLE_RECEPTION = "ROLE_RECEPTION",
    ROLE_DRIVER = "ROLE_DRIVER",
    ROLE_CONTROL_CAR = "ROLE_CONTROL_CAR",
    ROLE_ZEC = "ROLE_ZEC",
    ROLE_MANAGER = "ROLE_MANAGER",
    ROLE_WAREHOUSE = "ROLE_WAREHOUSE",
    ROLE_SYSTEM_ADMIN = "ROLE_SYSTEM_ADMIN"
}
